### ISSUE TITLE
enabled HDC controllerboard crashes sysinfo4.4 under AROS

### ISSUE THREAD

**Issue by mithrendal** [mras0/AmiEmu#1] opened 2022-04-27 12:46 UTC
Hi @mras0 😀
vAmiga Hdc controller is derived from AmiEmu right? 

crash happens before AmigaDos boot sequence shows up...

Heres is what it logs in XCode when running vAmiga

![image](https://user-images.githubusercontent.com/17108995/165519283-23ba4ddb-902b-4a6a-8513-80a534a40927.png)

and also vAmigaWeb version shows the same problem 
![image](https://user-images.githubusercontent.com/17108995/165519910-4f6ee7c4-1aed-4161-8099-46773fb44617.png)

in webversion shortly after the geometry message I see these following logs in the javascript console
![image](https://user-images.githubusercontent.com/17108995/165520267-f2f520ba-0cbf-4892-9c45-2e7ff1b594a8.png)

Is maybe AmiEmu immune to this bug ? Do you have an idea how this can be repaired? Must for sure be something what AROS does as it works flawlessly under Kick1.3.

for reference see the crashing sysinfo 4.4 at https://vamigaweb.github.io/doc/about.html 
it is the last demo at the very end of the page

**Comment by mras0** [comment] 2022-04-27 14:55
Confirmed (with or without the sysinfo disk). Doesn't seem to happen if I use shared folders or my PFS3 test HDF, so I suspect it's something with ROM filesystem (OFS+FFS). Maybe TD_GETGEOMETRY not being supported.

I'll investigate and see if I can fix it, then I can suggest what needs to be done to vAmiga.

**Comment by mithrendal** [comment] 2022-04-27 16:17
>with or without the sysinfo disk

the other demos on the [vAmigaWeb about page](https://vamigaweb.github.io/doc/about.html) do load normally using AROS despite HDC board enabled... quite strange no? These are also ADFs ... I mean what is the difference between the sysinfo ADF and the others ? It hangs very early ... is it maybe something inside the bootblock of the sysinfo adf?

>I'll investigate and see if I can fix it, then I can suggest what needs to be done to vAmiga.

thank you ❤ If it is too difficult we also could just disable your HDC board in vAmiga as default. And only enable it when the user drags some hdf files into it. On the other hand to have an empty hd0 per default was a nice feature.

**Comment by mras0** [comment] 2022-04-27 17:36
Debugged a bit further, and it seems like there's some issue with "plain" (i.e. non RDB) HDFs. More debugging to be follow... Unfortunately I haven't done the necessary work in [vAmigaSDL](https://github.com/mras0/vAmigaSDL) to support AROS so I can't check yet if the behavior matches.

> the other demos on the [vAmigaWeb about page](https://vamigaweb.github.io/doc/about.html) do load normally using AROS despite HDC board enabled... quite strange no? These are also ADFs ... I mean what is the difference between the sysinfo ADF and the others ? It hangs very early ... is it maybe something inside the bootblock of the sysinfo adf?

Is that the only configuration difference between the setups? The other setups seem to use custom bootloaders, while Sysinfo doesn't, so could you perhaps try with e.g. a WB disk disk and see if that also doesn't work while the demos do? I know I could check myself, but it's easier if we can parallelize the debugging :)

> thank you ❤ If it is too difficult we also could just disable your HDC board in vAmiga as default. And only enable it when the user drags some hdf files into it. On the other hand to have an empty hd0 per default was a nice feature.

If it's only an AROS issue, and I can't figure it out, HD could still be enabled for real KS roms, but let's see.

**Comment by mras0** [comment] 2022-04-27 18:14
Update: Try to change [this line](https://github.com/vAmigaWeb/vAmigaWeb/blob/f192b6120432ff317b62ca2c21d709bdaeb9b216/Emulator/Zorro/HdController.cpp#L493):

To say         mem.patch(ptr + devn_numBuffers,    u32(128)); // 2 is maybe ok...

**Comment by mithrendal** [comment] 2022-04-27 18:31
>Is that the only configuration difference between the setups?

yes

>The other setups seem to use custom bootloaders, while Sysinfo doesn't, so could you perhaps try with e.g. a WB disk disk and see if that also doesn't work while the demos do?

I observed the following behaviour:

when inserting a floppy disk at this stage ...
![image](https://user-images.githubusercontent.com/17108995/165593276-b054e063-d25e-419f-8a54-75642a582f71.png)

then AROS does not accept any disk (ADF) ... it does not begin to load it (due to the HDC board)

when making a reset or inserting the ADF very early on ... (cat eyes have not been drawn) 

then the demos load fine ...

the workbench gets stuck with a gray colored screen

but sysinfo4.4 ADF freaks out completely 

see here this picture

![image](https://user-images.githubusercontent.com/17108995/165592990-86d74a4a-2784-4d3c-a790-98d619dc39db.png)



the message `Warning: Unsupported cmd: 22 (TD_GETGEOMETRY)` is always in the logs even when no floppy disk has been inserted


I suspect that after the warning message GETGEOMETRY has been written to log it does not begin to boot from any ADF floppy disk anymore... my feeling is that it only loads the demos when the message is written to log after the boot process started...


EDIT: was so focused with testing and did not read your patch ... will try it now

**Comment by mithrendal** [comment] 2022-04-27 19:18
I don't know what I am doing but 

I replaced line 
`mem.patch(ptr + devn_numBuffers, u32(1));
` 

with
`mem.patch(ptr + devn_numBuffers, u32(128)); 
`

behaviour:
now it boots into sysinfo 4.4 😎 ... when disk loading begins very early (e.g. disk is already inserted + reset) 

when cat eyes are present it still refuses to load

warning about unkown cmd geometry is still in the logs

**Comment by mithrendal** [comment] 2022-04-27 19:31
UPDATE: with the patch ADF sysinfo 4.4 does indeed boot but later the buttons in sysinfo when you choose "boards" or "mem" do not work (nothing happens on click)

only when I disable HDC then sysinfo 4.4 boots + works correctly

EDIT: u32(2) boots too but does not work either...

**Comment by mras0** [comment] 2022-04-27 19:39
> I don't know what I am doing but
> 
> I replaced line `mem.patch(ptr + devn_numBuffers, u32(1)); `
> 
> with `mem.patch(ptr + devn_numBuffers, u32(128)); `
> 
> behaviour: now it boots into sysinfo 4.4 😎

Great!

. ... when disk loading begins very early (e.g. disk is already inserted + reset)
> 
> when cat eyes are present it still refuses to load

Not sure what you mean here, "cat eyes" is the same as the "insert disk" screen with normal KS FWIW. You boot normlly and inserting SysInfo adf dosn't work? 

> 
> warning about unkown cmd geometry is still in the logs

I think you can ignore that, I checked AROS source, and it should work even if this command isn't supported. 

> UPDATE: with the patch ADF sysinfo 4.4 does indeed boot but later the buttons in sysinfo when you choose "boards" or "mem" do not work (nothing happens on click)

Works for me in AmiEmu, but I'll have to do more work to check it properly in vAmigaSDL. Stay tuned.

**Comment by mithrendal** [comment] 2022-04-27 20:01
>You boot normlly and inserting SysInfo adf dosn't work?

scenario 1:
power up and wait to cat eyes ... 
insert adf file 
nothing happens now... it is stuck
(hitting reset) 
screen flashes and floppy loading begins

scenario 2:
inserting floppy
power up 
screen flashes and floppy loading begins
 

------
without hdc enabled it does not get stuck in scenario 1. 
 

EDIT: I just pushed out a new version of vAmigaWeb which removes the default HDC board activation. It is only activated now when a hdf is dragged into vAmigaWeb. (when we solved this we can reactivate the default HDC board...

**Comment by mras0** [comment] 2022-05-01 09:31
Closing this one, as I think it should be fixed now. You can always open another issue if you notice anything else is wrong. Thanks for catching this.

The warning about TD_GETGEOMETRY will still be there, but it's inconsequential, and btw it would have to be handled by the vAmgia code since the expansion ROM just forwards all IORequests to the host.

**Closed as completed by mras0** 2022-05-01 09:31 UTC
Labels: bug
